

export const phonesData = [
    {
      id: 1,
      model: "Sunisa Foundation Cream",
      desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
      price: 1299,
      image: "./assets/Sunisa.jpeg",
      qty: 6,
    },
    {
      id: 2,
      model: "Fogg Body Perfume",
      desc: "Experience the luxury of Fogg Perfume, lasting freshness in every spray.",
      price: 1199,
      image: "./assets/fogg.jpeg",
      qty: 0,
    },
    {
      id: 3,
      model: "Nivea Body Lotion",
      desc: "Softens and nourishes your skin, leaving it smooth and hydrated Nivea body lotion.",
      price: 1099,
      image: "./assets/Nivea Body.jpeg",
      qty: 1,
    },
    {
      id: 4,
      model: "Parachute Oil",
      desc: "Provides deep nourishment, leaving your hair and skin soft and healthy parachute oil.",
      price: 1099,
      image: "./assets/parachuteoil.jpeg",
      qty: 1,
    },
    {
      id: 5,
      model: "Sunisa Foundation Cream",
      desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
      price: 1299,
      image: "./assets/lip.jpg",
      qty: 6,
    },
    {
      id: 6,
      model: "Fogg Body Perfume",
      desc: "Experience the luxury of Fogg Perfume, lasting freshness in every spray.",
      price: 1199,
      image: "./assets/wipes.jpg",
      qty: 0,
    },
    {
      id: 7,
      model: "Nivea Body Lotion",
      desc: "Softens and nourishes your skin, leaving it smooth and hydrated Nivea body lotion.",
      price: 1099,
      image: "./assets/1.jpg",
      qty: 1,
    },
    {
      id: 8,
      model: "Parachute Oil",
      desc: "Provides deep nourishment, leaving your hair and skin soft and healthy parachute oil.",
      price: 1099,
      image: "./assets/2.jpg",
      qty: 1,
    },
    {
      id: 1,
      model: "Sunisa Foundation Cream",
      desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
      price: 1299,
      image: "./assets/3.jpg",
      qty: 6,
    },
    {
      id: 2,
      model: "Fogg Body Perfume",
      desc: "Experience the luxury of Fogg Perfume, lasting freshness in every spray.",
      price: 1199,
      image: "./assets/4.jpg",
      qty: 0,
    },
    {
      id: 3,
      model: "Nivea Body Lotion",
      desc: "Softens and nourishes your skin, leaving it smooth and hydrated Nivea body lotion.",
      price: 1099,
      image: "./assets/5.jpg",
      qty: 1,
    },
    {
      id: 4,
      model: "Parachute Oil",
      desc: "Provides deep nourishment, leaving your hair and skin soft and healthy parachute oil.",
      price: 1099,
      image: "./assets/parachuteoil.jpeg",
      qty: 1,
    },
    {
      id: 1,
      model: "Sunisa Foundation Cream",
      desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
      price: 1299,
      image: "./assets/Sunisa.jpeg",
      qty: 6,
    },
    {
      id: 2,
      model: "Fogg Body Perfume",
      desc: "Experience the luxury of Fogg Perfume, lasting freshness in every spray.",
      price: 1199,
      image: "./assets/fogg.jpeg",
      qty: 0,
    },
    {
      id: 3,
      model: "Nivea Body Lotion",
      desc: "Softens and nourishes your skin, leaving it smooth and hydrated Nivea body lotion.",
      price: 1099,
      image: "./assets/Nivea Body.jpeg",
      qty: 1,
    },
    {
      id: 4,
      model: "Parachute Oil",
      desc: "Provides deep nourishment, leaving your hair and skin soft and healthy parachute oil.",
      price: 1099,
      image: "./assets/parachuteoil.jpeg",
      qty: 1,
    },
  ];
  

  