export const phonesData = [
  {
    id: 1,
    model: "Sunisa Foundation Cream",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "Sunisa.jpeg",
    qty: 6,
  },
  {
    id: 2,
    model: "Fogg Body Perfume",
    desc: "Experience the luxury of Fogg Perfume, lasting freshness in every spray.",
    price: 1199,
    image: "fogg.jpeg",
    qty: 0,
  },
  {
    id: 3,
    model: "Nivea Body Lotion",
    desc: "Softens and nourishes your skin, leaving it smooth and hydrated Nivea body lotion.",
    price: 1099,
    image: "Nivea Body.jpeg",
    qty: 1,
  },
  {
    id: 4,
    model: "Parachute Oil",
    desc: "Provides deep nourishment, leaving your hair and skin soft and healthy parachute oil.",
    price: 1099,
    image: "parachuteoil.jpeg",
    qty: 1,
  },
  {
    id: 5,
    model: "Sunisa Foundation Cream",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "lip.jpg",
    qty: 6,
  },
  {
    id: 6,
    model: "Fogg Body Perfume",
    desc: "Experience the luxury of Fogg Perfume, lasting freshness in every spray.",
    price: 1199,
    image: "wipes.jpg",
    qty: 0,
  },
  {
    id: 7,
    model: "Nivea Body Lotion",
    desc: "Softens and nourishes your skin, leaving it smooth and hydrated Nivea body lotion.",
    price: 1099,
    image: "1.jpg",
    qty: 1,
  },
  {
    id: 8,
    model: "Parachute Oil",
    desc: "Provides deep nourishment, leaving your hair and skin soft and healthy parachute oil.",
    price: 1099,
    image: "2.jpg",
    qty: 1,
  },
  {
    id: 9,
    model: "Sunisa Foundation Cream",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "3.jpg",
    qty: 6,
  },
  // ... (continue for other items)

  {
    id: 10,
    model: "Nivea Shaving Foam",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "4.jpg",
    qty: 6,
  },
  {
    id: 11,
    model: "Nivea Shaving Foam",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },

  {
    id: 12,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "9 (1).jpg",
    qty: 8,
  },
  {
    id: 13,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "9 (2).jpg",
    qty: 0,
  },

  {
    id: 14,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "9 (3).jpg",
    qty: 0,
  },

  {
    id: 15,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "9 (4).jpg",
    qty: 0,
  },

  {
    id: 16,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "9 (5).jpg",
    qty: 0,
  },

  {
    id: 17,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "9 (6).jpg",
    qty: 0,
  },
  {
    id: 18,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "9 (7).jpg",
    qty: 0,
  },

  {
    id: 19,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "9 (8).jpg",
    qty: 0,
  },

  {
    id: 20,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "9 (9).jpg",
    qty: 0,
  },

  {
    id: 21,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "9 (10).jpg",
    qty: 0,
  },

  {
    id: 22,
    model: "Sunisa Foundation Cream",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "9 (11).jpg",
    qty: 6,
  },
  {
    id: 23,
    model: "Fogg Body Perfume",
    desc: "Experience the luxury of Fogg Perfume, lasting freshness in every spray.",
    price: 1199,
    image: "9 (12).jpg",
    qty: 0,
  },
  {
    id: 24,
    model: "Nivea Body Lotion",
    desc: "Softens and nourishes your skin, leaving it smooth and hydrated Nivea body lotion.",
    price: 1099,
    image: "9 (13).jpg",
    qty: 1,
  },
  {
    id: 25,
    model: "Parachute Oil",
    desc: "Provides deep nourishment, leaving your hair and skin soft and healthy parachute oil.",
    price: 1099,
    image: "9(14).jpg",
    qty: 1,
  },
  {
    id: 26,
    model: "Sunisa Foundation Cream",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "9 (15).jpg",
    qty: 6,
  },
  {
    id: 27,
    model: "Fogg Body Perfume",
    desc: "Experience the luxury of Fogg Perfume, lasting freshness in every spray.",
    price: 1199,
    image: "9 (16).jpg",
    qty: 0,
  },
  {
    id: 28,
    model: "Nivea Body Lotion",
    desc: "Softens and nourishes your skin, leaving it smooth and hydrated Nivea body lotion.",
    price: 1099,
    image: "9 (17).jpg",
    qty: 1,
  },
  {
    id: 29,
    model: "Young Age Magic Foundation",
    desc: "Provides deep nourishment, leaving your hair and skin soft and healthy parachute oil.",
    price: 1099,
    image: "9 (18).jpg",
    qty: 10,
  },

  {
    id: 30,
    model: "Sunisa Foundation Cream",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "9(19).jpg",
    qty: 6,
  },
  // ... (continue for other items)

  {
    id: 31,
    model: "Nivea Shaving Foam",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "4.jpg",
    qty: 6,
  },
  {
    id: 32,
    model: "Nivea Shaving Foam",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "4.jpg",
    qty: 0,
  },

  {
    id: 33,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },
  {
    id: 34,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },

  {
    id: 35,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },

  {
    id: 36,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },

  {
    id: 37,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },

  {
    id: 38,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },
  {
    id: 39,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },

  {
    id: 40,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },

  {
    id: 41,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },

  {
    id: 42,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },

  {
    id: 43,
    model: "Sunisa Foundation Cream",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "Sunisa.jpeg",
    qty: 6,
  },
  {
    id:44,
    model: "Fogg Body Perfume",
    desc: "Experience the luxury of Fogg Perfume, lasting freshness in every spray.",
    price: 1199,
    image: "fogg.jpeg",
    qty: 0,
  },
  {
    id: 45,
    model: "Nivea Body Lotion",
    desc: "Softens and nourishes your skin, leaving it smooth and hydrated Nivea body lotion.",
    price: 1099,
    image: "Nivea Body.jpeg",
    qty: 1,
  },
  {
    id: 46,
    model: "Parachute Oil",
    desc: "Provides deep nourishment, leaving your hair and skin soft and healthy parachute oil.",
    price: 1099,
    image: "parachuteoil.jpeg",
    qty: 1,
  },
  {
    id: 47,
    model: "Sunisa Foundation Cream",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "lip.jpg",
    qty: 6,
  },
  {
    id: 48,
    model: "Fogg Body Perfume",
    desc: "Experience the luxury of Fogg Perfume, lasting freshness in every spray.",
    price: 1199,
    image: "wipes.jpg",
    qty: 0,
  },
  {
    id: 49,
    model: "Nivea Body Lotion",
    desc: "Softens and nourishes your skin, leaving it smooth and hydrated Nivea body lotion.",
    price: 1099,
    image: "1.jpg",
    qty: 1,
  },
  {
    id: 50,
    model: "Parachute Oil",
    desc: "Provides deep nourishment, leaving your hair and skin soft and healthy parachute oil.",
    price: 1099,
    image: "2.jpg",
    qty: 1,
  },
  {
    id: 51,
    model: "Sunisa Foundation Cream",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "3.jpg",
    qty: 6,
  },
  // ... (continue for other items)

  {
    id: 52,
    model: "Nivea Shaving Foam",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "4.jpg",
    qty: 6,
  },
  {
    id: 53,
    model: "Nivea Shaving Foam",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "4.jpg",
    qty: 0,
  },

  {
    id: 54,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },
  {
    id: 55,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "perfectrediancefoundation.jpg",
    qty: 0,
  },

  {
    id: 56,
    model: "Mac Foundation",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "macfoundation.jpg",
    qty: 0,
  },

  {
    id: 57,
    model: "Green Tea",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "greentea.jpg",
    qty: 0,
  },

  {
    id: 58,
    model: "Huda Beauty Concealer",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "hudabeautyconcealer.jpg",
    qty: 0,
  },

  {
    id: 59,
    model: "Matte Compact Powder",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "mattecompactpowder.jpg",
    qty: 0,
  },
  {
    id: 60,
    model: "Baby Skin Reduction Powder",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "babyskinreductionpowder.jpg",
    qty: 0,
  },

  {
    id: 61,
    model: "Kiss Beauty Skin Powder",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "kissbeautyskinpowder.jpg",
    qty: 0,
  },

  {
    id: 62,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },

  {
    id: 63,
    model: "Micro Blusher",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "5.jpg",
    qty: 0,
  },

  {
    id: 64,
    model: "Arjun",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "arjun.png",
    qty: 0,
  },
];
