export const phonesData = [
  {
    id: 1,
    model: "Sunisa Foundation Cream",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "Sunisa.jpeg",
    qty: 6,
  },
  {
    id: 2,
    model: "Fogg Body Perfume",
    desc: "Experience the luxury of Fogg Perfume, lasting freshness in every spray.",
    price: 1199,
    image: "fogg.jpeg",
    qty: 0,
  },
  {
    id: 3,
    model: "Nivea Body Lotion",
    desc: "Softens and nourishes your skin, leaving it smooth and hydrated Nivea body lotion.",
    price: 1099,
    image: "Nivea Body.jpeg",
    qty: 1,
  },
  {
    id: 4,
    model: "Parachute Oil",
    desc: "Provides deep nourishment, leaving your hair and skin soft and healthy parachute oil.",
    price: 1099,
    image: "parachuteoil.jpeg",
    qty: 1,
  },
  {
    id: 5,
    model: "Sunisa Foundation Cream",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "lip.jpg",
    qty: 6,
  },
  {
    id: 6,
    model: "Fogg Body Perfume",
    desc: "Experience the luxury of Fogg Perfume, lasting freshness in every spray.",
    price: 1199,
    image: "wipes.jpg",
    qty: 0,
  },
  {
    id: 7,
    model: "Nivea Body Lotion",
    desc: "Softens and nourishes your skin, leaving it smooth and hydrated Nivea body lotion.",
    price: 1099,
    image: "1.jpg",
    qty: 1,
  },
  {
    id: 8,
    model: "Parachute Oil",
    desc: "Provides deep nourishment, leaving your hair and skin soft and healthy parachute oil.",
    price: 1099,
    image: "2.jpg",
    qty: 1,
  },
  {
    id: 9,
    model: "Sunisa Foundation Cream",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "3.jpg",
    qty: 6,
  },
  // ... (continue for other items)

  {
    id: 10,
    model: "Nivea Shaving Foam",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "4.jpg",
    qty: 6,
  },
  {
    id: 11,
    model: "Nivea Shaving Foam",
    desc: "3 in 1 Air Cushion CC and BB Cream Foundation offers full coverage with a lightweight feel.",
    price: 1299,
    image: "4.jpg",
    qty: 0,
  },
];
